language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  api_key:
    secure: a0eG0FpMCri8zra1PEdtvCvbHVudRpSmhs71h4AXZko8bDYGzPLHworSmBIODDmzLYXD1adqTK2kL/MCOL9rsXZUP6Gzk9jK7dBDJQwkoNgg+K9mV5ZMhiMKEcv5nj6WsF5vP0KVkplAt8TWXDHpXXRBaK6vYs5aPPF5D8ta9iEed34xk90Q1a+IRzYx/k2SF6hj9v4xb0ZYLgd1pSL+r7Jk70mIcXcMQwwtvL2XPIFco8HE4c+/QZynzYQWVOTk+JFMRKuStwRnbZFSmZqCx6C3l+EWge9ls3D/Aqk4Kq5z+/Vg3roeXh1vzxVqQEMnkrWOr6nxfYcxQHMhuXY/HOnHLxZK0fd7e329akwPCkY8QaMY0YY3O2irwa8qOeXiUnVFNGeCwS8s0Zwnm1V154XwmK1cjIOeM5gBOYArmR+xN485sN8LBI7sGwzPbiP56R3m3RYxWWyjNkLFRCAmEfGF4whaYqf+0IiYc5aw8cq55BZJV3unYE+TAwd2xR/Wi+5PV7GcqfZtk4vqQpkofAtUqZA62xXG50tqcFBp9xqtb2yP5WH7QJD2uwoyHDN8ydDE9dmxixIDa++v9SLcoUGQmu479vT+fC6DyvRMMNwmod2ppUWbctdOXwWKdwDpYScY1V3u37vOttWOmmpfudJIIPqrpDsboUukMdR0CdY=
  email:
    secure: Dlsa8qsr/JDwaUw8FC5+SAP3vzz4BstO1lUkmKmftUUFA5aYA2z4ilrBHueFMcuYtAGpVdidfoz78/MSc+Vn1K1hGyazbmjEHy1sGyPOgrqfRcb20DixGx1aANiRLkETyc61GLU8SGvTF31SyKA8Dz+c67nBcGoMBfS0CF31LpnvUfpVX0JcHNg+IX/n4O3Dj21w5qM4uKZLpI/SYWd5Yufl7hQA181ZkL3BygY33BxNCQQvEguHsnGd+z4UraUtcbvAMjbbdfbUyC97tPsqZnAMmQ+FRmSu+CTSSg8Md1p84Ux7LM/YyefRSf9PO4Uv8O8+kddd7giDxdrTAmjhdkuz7ZMm5MgdoxYRP8aBM0OePyxNBCnc/qUv4oh6+X3KbhQ/Pa2Y2Ej4IgLQssSrdna+29PRgvvq6ATqjn8oDA/uX23yPUCbtIk8F/8XwD3db+yVOFQCE+BHQGLfH686RVOMcojrpJolNSJo58a0wU8lii1sgxG3G6e1hhek7VR6tC0ItLJ8gSp/FdbrsDPloWIbvbMRr0sc0oVwjFfszSWSAgOfZDOHux9oP/bOyDikQuwQgHoZ1unCNIkpNClp7ocKhkKKQn3jdvEu8ZgG4z0WBvvLHTKONsdX1kLQC+jnU2txNBUloBfYyMDYPImTIJgCU1vbOvAW6hrL3xsB6PQ=
  provider: npm
  skip_cleanup: true
  on:
    tags: true
